/**
 * VMCS
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface Coin {
  id: number;
  /**
   * ex. $1, 50 c
   */
  name: string;
  /**
   * face value ($1 for 100)
   */
  value: number;
  /**
   * stock
   */
  quantity: number;
  weight: number;
}
