server:
  port: 8081
  shutdown: graceful

#spring:
#  datasource:
#    url: jdbc:postgresql://localhost:5432/vmcs
#    username: user1
#    password: pass1
#  jpa:
#    properties:
#      hibernate:
#        # The SQL dialect makes Hibernate generate better SQL for the chosen database
#        dialect: org.hibernate.dialect.PostgreSQLDialect
#    hibernate:
#      # Hibernate ddl auto (create, create-drop, validate, update)
#      ddl-auto: update
#    show-sql: true

spring:
  lifecycle:
    # Allow grace timeout period for 10 seconds
    timeout-per-shutdown-phase: 10s
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:file:./db/vmcs;NON_KEYWORDS=USER,VALUE
    username: user1
    password: pass1
  h2:
    path: /h2
    console:
      # Web management interface: http://localhost:8081/h2-console
      enabled: true
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
    hibernate:
      # Hibernate ddl auto (create, create-drop, validate, update)
      ddl-auto: update
    show-sql: true

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    shutdown:
      enabled: true