/**
 * VMCS
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface InlineObject1 {
  id: number;
  /**
   * ex. Maintainer
   */
  role: InlineObject1.RoleEnum;
  /**
   * 6 alphanumeric chars
   */
  password: string;
  /**
   * [\'login\', \'logout\']
   */
  status: InlineObject1.StatusEnum;
}
export namespace InlineObject1 {
  export type RoleEnum = 'Customer' | 'Maintainer' | 'Controller';
  export const RoleEnum = {
    Customer: 'Customer' as RoleEnum,
    Maintainer: 'Maintainer' as RoleEnum,
    Controller: 'Controller' as RoleEnum,
  };
  export type StatusEnum = 'login' | 'logout';
  export const StatusEnum = {
    Login: 'login' as StatusEnum,
    Logout: 'logout' as StatusEnum,
  };
}
